from sconsproject import helpers

# Bring in the SCons environment.
Import('env')

# Define our test suites. Each tuple defines a test as follows:
#
#   (suite_source, support_source0, support_source1, ..., MPI_rank_range)
#
# The support sources are optional, as is the MPI rank range.
common = ('assert.cc', 'assertions.cc', 'globals.cc', 'checks.cc', 'stacktrace.cc', 'func.cc')
suites = [
    ('assert_suite.t.hh',) + common,
    ('group_context_suite.t.hh', 'omp_lock.cc',) + common,
    ('error_suite.t.hh',),
]

# Define libraries to link against.
libs = [] + env.get('LIBS', [])

# Call the helper.
execfile(helpers.get_build_tests_script(), globals())
