Import('env', 'obj_map')
Export('env', 'obj_map')

comm = ('comm.cc', 'data_type.cc', 'request.cc', 'requests.cc', 'logger.cc', 'init.cc', 'assert.cc')

srcs = (
    ('comm_suite.t.hh',) + comm + (range(1, 10),),
)

libs = ['containers', 'logging', 'system', 'memory', 'debug'] + env.get('LIBS', [])

for src in srcs:
    if isinstance(src, str):
        objs = []
    else:
        if len(src) and isinstance(src[-1], (list, tuple)):
            ranks = src[-1]
            src = src[:-1]
        else:
            ranks = []
        objs = src[1:] if (len(src) > 1) else []
        objs = [obj_map[o] for o in objs]
        src = src[0]
    env.CxxTest([src] + objs, ranks=ranks, LIBS=libs)
