from sconsproject import helpers

# Bring in the SCons environment.
Import('env')

# Define our test suites. Each tuple defines a test as follows:
#
#   (suite_source, support_source0, support_source1, ..., MPI_rank_range)
#
# The support sources are optional, as is the MPI rank range.
suites = [
    ('std_vector_suite.t.hh',),
    ('vector_view_suite.t.hh',),
    ('vector_suite.t.hh',),
    ('set_suite.t.hh',),
    ('map_suite.t.hh',),
    ('multimap_suite.t.hh',),
    ('fibre_suite.t.hh',),
    ('po2_ring_buffer_suite.t.hh',),
    ('range_set_suite.t.hh',),
    ('range_map_suite.t.hh',),
    ('range_multimap_suite.t.hh',),
    ('counts_suite.t.hh',),
    ('csr_suite.t.hh',),
    ('algorithms_suite.t.hh',),
    ('enumerator_suite.t.hh',),
    ('sort_permute2_iter_suite.t.hh',),
    ('random_suite.t.hh', 'random.cc'),
]

# Define libraries to link against.
libs = ['debug', 'system'] + env.get('LIBS', [])

# Call the helper.
execfile(helpers.get_build_tests_script(), globals())
