from sconsproject import helpers

# Bring in the SCons environment.
Import('env')

# Define our test suites. Each tuple defines a test as follows:
#
#   (suite_source, support_source0, support_source1, ..., MPI_rank_range)
#
# The support sources are optional, as is the MPI rank range.
suites = [
    ('xml_suite.t.hh', 'bad_option.cc', 'option.cc', 'dictionary.cc', 'xml.cc'),
    ('dictionary_suite.t.hh', 'bad_option.cc', 'option.cc', 'dictionary.cc', 'xml.cc'),
    ('xml_dict_suite.t.hh', 'bad_option.cc', 'xml_dict.cc'),
    ('cmd_line_suite.t.hh', 'cmd_line.cc', 'bad_option.cc', 'option.cc', 'dictionary.cc', 'format.cc'),
]

# Define libraries to link against.
libs = ['regexp', 'containers', 'logging', 'system', 'memory', 'debug'] + env.get('LIBS', [])

# Call the helper.
execfile(helpers.get_build_tests_script(), globals())
