from sconsproject import helpers

# Bring in the environment into our locals().
Import('env')

# Set the project name. This is passed on to sub-scripts.
env['SUBPROJ'] = 'containers'

# Call the helper script.
execfile(helpers.get_build_sub_project_script(), globals())
