from sconsproject import helpers

# Bring in the SCons environment.
Import('env')

# Declare subdirectories.
sub_dirs = []

# Define destination subdirectory, i.e. where these binaries will
# be placed.
dst_dir = '#' + env['BUILD'] + '/exs/'

# Define libraries to use.
libs = ['hpcmpi', 'profile', 'logging', 'containers', 'debug', 'system'] + env.get('LIBS', [])

# Declare local sources. Format is:
#
#   ('<binary name>', '<source 0>', '<source 1>', ...)
sources = [
    # ('', '', ''),
]

# Add .cu files.
if env['WITH_CUDA']:
    sources.extend([
        ('select_thrust', 'select_thrust.cu', {'LINK': 'g++', 'LIBS': ['cuda', 'cudart'], 'LIBPATH': env.get('LIBPATH') + ['/usr/lib/nvidia-304']}),
    ])

# Call the helper.
execfile(helpers.get_build_apps_script(), globals())
