from sconsproject import helpers

# Bring in the SCons environment.
Import('env')

# Define our test suites. Each tuple defines a test as follows:
#
#   (suite_source, support_source0, support_source1, ..., MPI_rank_range)
#
# The support sources are optional, as is the MPI rank range.
suites = [
    ('stdout_suite.t.hh', 'stdout.cc', 'logger.cc'),
    ('file_suite.t.hh', 'file.cc', 'logger.cc'),
    ('omp_file_suite.t.hh', 'omp_file.cc', 'file.cc', 'logger.cc', 'globals.cc', 'stack.cc'),
    ('globals_suite.t.hh', 'file.cc', 'logger.cc', 'globals.cc', 'stack.cc', 'instrument.cc'),
    ('instrument_suite.t.hh', 'stdout.cc', 'logger.cc', 'globals.cc', 'stack.cc', 'instrument.cc'),
]

# Define libraries to link against.
libs = ['containers', 'system', 'memory', 'debug'] + env.get('LIBS', [])

# Call the helper.
execfile(helpers.get_build_tests_script(), globals())
